miner_values:
  min: 1
  max: 10
treecutter_values:
  min: 1
  max: 10
fishing_values:
  min: 1
  max: 10
build_values:
  min: 1
  max: 10
farm_values:
  min: 1
  max: 10
doctor_material: REDSTONE
debug: true