miner_values:
  GOLD_ORE: 3 # money given per mined block all blocks available found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  EMERALD_ORE: 5
  MOSSY_COBBLESTONE: 1
  IRON_ORE: 2
treecutter_values:
  LOG: 2
fishing_values:
  min: 1
  max: 10
build_values:
  GRAVEL: 2
  SAND: 3
  CLAY: 5
farm_values:
  WHEAT: 2
  BEETROT: 2
  SUGAR: 2
doctor_material: REDSTONE
debug: false