name: Jobs
version: '${project.version}'
main: net.danh.jobs.Jobs
depend: [Vault, PlaceholderAPI]
authors: [VoChiDanh]
commands:
  nghe:
  chonnghe:
  doinghe:
  danhsachnghe:
  caydao:
  thuocbacsi:
  115:
  hangcam:
  jobs:
